const data = [
    {
        projectName: 'Behror',
        image1: '',
        image2: '',
        image3: '',
        quote: '',
        desc: '',
        type: 'outdoor',
        subcat: 'resdential',
        plot_area: '936 Square Feet',
        Buid_up_area: '1854 Square Feet',
        completed_in: '2013',
    },
    {
        projectName: 'Budh Vihar',
        image1: '',
        image2: '',
        image3: '',
        quote: '',
        desc: '',
        type: 'outdoor',
        subcat: 'resdential',
        plot_area: '936 Square Feet',
        Buid_up_area: '1854 Square Feet',
        completed_in: '2013',
    },
    {
        projectName: 'Budh Vihar',
        image1: '',
        image2: '',
        image3: '',
        quote: '',
        desc: '',
        type: 'outdoor',
        subcat: 'resdential',
        plot_area: '936 Square Feet',
        Buid_up_area: '1854 Square Feet',
        completed_in: '2013',
    },
    {
        projectName: 'Budh Vihar',
        image1: '',
        image2: '',
        image3: '',
        quote: '',
        desc: '',
        type: 'outdoor',
        subcat: 'resdential',
        plot_area: '936 Square Feet',
        Buid_up_area: '1854 Square Feet',
        completed_in: '2013',
    },
]